server.error.whitelabel.enabled=false
spring.application.name=SpringRESTful
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.data.rest.base-path=/api
spring.jpa.defer-datasource-initialization=true
okta.oauth2.issuer=https://dev-30779887.okta.com/oauth2/default
okta.oauth2.audience=api://default
#server.port=8081
okta.oauth2.groupsClaim=Groups